/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageGarage;

import Process.Check;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class TiepNhanSuaChua extends javax.swing.JInternalFrame {
    private String header[] = {"tên chủ xe","biển số", "hiệu xe", "SDT", "địa chỉ", "ngày nhận",};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    /**
     * Creates new form TiepNhanSuuChua
     */
    public TiepNhanSuaChua() {
        initComponents();
        //idHX= new Lis<Integer>();
        LoadDataCombo();
        loadTbl();
        
    }
    
    private void LoadDataCombo(){
     Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://127.0.0.1:1433;databaseName=GARAOTO";

        try {
            conn = DriverManager.getConnection(dbURL,"sa","1");
            // gòi. dm lô tuyồồn

            // Câu lệnh xem dữ liệu
            String sql = "select idhx, tenhx from hieuxe";

            // Tạo đối tượng thực thi câu lệnh Select
            st = conn.createStatement();

            // Thực thi 
            rs = st.executeQuery(sql);
            Vector data = null;
            DefaultComboBoxModel cmbModel = new DefaultComboBoxModel();

            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không có lượt tiếp nhận mới!");
                jComboBox1.setEnabled(false);
                
                
                
                
                return;
            }

            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getInt("idhx"));
                data.add(rs.getString("tenhx"));

                // Thêm một dòng vào table model
                cmbModel.addElement(data);
            }

             jComboBox1.setModel(cmbModel);

            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
              
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTenChuXe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtBienSo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtSDT = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        mStatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tiếp Nhận Sửa Chữa");

        jLabel1.setText("Tên Chủ Xe");

        jLabel3.setText("Biển Số");

        jLabel4.setText("Địa chỉ");

        jtxtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDiaChiActionPerformed(evt);
            }
        });

        jLabel5.setText("Hiệu xe");

        jLabel6.setText("SDT");

        jtxtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSDTActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên Chủ Xe", "Biển Số", "Hiệu Xe", "SDT", "Địa chỉ", "Ngày Nhận"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tiếp Nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mStatus.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(297, 297, 297))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtxtTenChuXe, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                            .addComponent(jtxtDiaChi))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtxtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(mStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTenChuXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtBienSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDiaChiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        int indexHX = jComboBox1.getSelectedIndex();
        if(indexHX <0) // khong ma nao duoc chon.
            return;
        Vector itemMaTN = (Vector)jComboBox1.getSelectedItem();
        String dbURL = "jdbc:sqlserver://127.0.0.1:1433;databaseName=GARAOTO";
        String insert = "INSERT INTO TIEPNHAN (TENKH,BIENSO,idHX,DIACHI,SDT,NGAYNHAN) VALUES(?,?,?,?,?,getdate())";
        
        try {
            conn = DriverManager.getConnection(dbURL,"sa","1");
            ps = conn.prepareStatement(insert);
        } catch (SQLException ex) {
            Logger.getLogger(TiepNhanSuaChua.class.getName()).log(Level.SEVERE, "Loi connect", ex);
        }
            
        try {
            if(Check.checkNum(this.jtxtTenChuXe.getText())==true){
                JOptionPane.showMessageDialog(null, "Tên khách hàng không được có số","Thông báo lỗi",1);
                return;
            }else
            if(Check.checkSb(this.jtxtTenChuXe.getText())==true){
                JOptionPane.showMessageDialog(null, "Tên khách hàng không được có kí tự đặc biệt","Thông báo lỗi",1);
                return;
            }else
            if(Check.checkNum2(this.jtxtSDT.getText())==true){
                JOptionPane.showMessageDialog(null, "Số điện thoại không được nhập chữ","Thông báo lỗi",2);
                return;
            }
            
            
            
            ps.setString(1, jtxtTenChuXe.getText());
            ps.setString(2, jtxtBienSo.getText());
  //          ps.setString(6,jtxtNgayNhan.getText());
            ps.setString(4, jtxtDiaChi.getText());
            ps.setString(5, jtxtSDT.getText());
            ps.setInt(3, Integer.parseInt(itemMaTN.get(0).toString()));
            
            
          
            int ret = ps.executeUpdate();
            mStatus.setText("Tiếp nhận thành công.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), e.getLocalizedMessage(), 1);
            e.printStackTrace();
            
         // tạm xong rồi. m làm mấy cái bắt lỗi giao diên, nhập tên blabla đi. ko làm đc kêu tuyến   
            
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }

                if (rs != null) {
                    rs.close();
                }

                if (ps != null) {
                    ps.close();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
        loadTbl();

                                      
                                       

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSDTActionPerformed
    private void loadTbl(){
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        String dbURL = "jdbc:sqlserver://127.0.0.1:1433;databaseName=GARAOTO;user=sa;password=1";

        int index = jComboBox1.getSelectedIndex();
        if(index <0) // khong kho nao duoc chon.
            return;
        Vector item = (Vector)jComboBox1.getSelectedItem();
  //      int idTN = Integer.parseInt(item.get(0).toString());
        
        try {
            conn = DriverManager.getConnection(dbURL);

            // măt lặặt duy tăt unikey cho bô. duma
            // Câu lệnh xem dữ liệu
            String sql = "select * from tiepnhan where day(ngaynhan)=day(getdate()) and month(ngaynhan)=month(getdate()) and year(ngaynhan)=year(getdate())";
            

            // Tạo đối tượng thực thi câu lệnh Select
            st = conn.createStatement();

            // Thực thi 
            rs = st.executeQuery(sql);
            Vector data = null;

            tblModel.setRowCount(0);

            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "CTSC khong co!");
                return;
            }

            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("tenkh"));
                data.add(rs.getString("bienso"));
                data.add(rs.getString("idhx"));
                data.add(rs.getString("sdt"));
                data.add(rs.getString("diachi"));
                data.add(rs.getString("ngaynhan"));
                // Thêm một dòng vào table model
                tblModel.addRow(data);
            }

            jTable1.setModel(tblModel); // Thêm dữ liệu vào table

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtBienSo;
    private javax.swing.JTextField jtxtDiaChi;
    private javax.swing.JTextField jtxtSDT;
    private javax.swing.JTextField jtxtTenChuXe;
    private javax.swing.JLabel mStatus;
    // End of variables declaration//GEN-END:variables
}
